<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="MySql.Data" Version="9.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="financeiroApi.Tests\**\*.cs" />
    <Content Remove="financeiroApi.Tests\**" />
    <None Remove="financeiroApi.Tests\**" />
    <EmbeddedResource Remove="financeiroApi.Tests\**" />
  </ItemGroup>

</Project>
